apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  labels:
    app: odoo
    env: prod
  namespace: ics-webapp
spec:
  storageClassName: manual
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi

