apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: ics-webapp
  labels:
    env: prod
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "docker_postgres",
           "Group": "Servers",
           "Host": "postgres",
           "Port": 5432,
           "MaintenanceDB": "postgres",
           "Username": "odoo_user",
           "SSLMode": "prefer"
          }
       }
   }

