apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: pg-admin
  namespace: ics-webapp
  labels:
    env: prod
    app: pg-admin
data:
  PGADMIN_DEFAULT_PASSWORD: cGdhZG1pbg==

