apiVersion: v1
kind: Service
metadata:
  name: ics-webapp
  labels:
    app: ics-webapp
    env: prod

  namespace: ics-webapp

spec:
  type: NodePort
  selector:
    app: ics-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

